import {
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Building2,
  Calendar,
  CalendarIcon,
  CheckCircle,
  ClipboardCopy,
  Clock,
  Eye,
  FileText,
  FileTextIcon,
  FolderInput,
  FolderTree,
  LibraryIcon,
  Loader2,
  LoaderCircle,
  MailOpen,
  PanelsTopLeft,
  Pencil,
  Printer,
  RefreshCw,
  RotateCw,
  ScaleIcon,
  Settings,
  LucideTrash2 as Trash2,
  UserIcon,
  LucideUserPlus2 as UserPlus2,
  Users,
  UsersIcon,
  X,
  XCircle,
} from "lucide-react";

export const Icons = {
  loading: LoaderCircle,
  spinner: Loader2,
  close: X,
  edit: Pencil,
  trash: Trash2,
  settings: Settings,

  // Navigation
  sidebarToggle: PanelsTopLeft,
  rightArrow: ArrowRight,
  externalLink: ArrowUpRight,

  // Cases
  cases: FileText,
  caseImports: FolderInput,
  caseGroups: FolderTree,

  // Organization
  organization: Building2,
  team: Users,
  analytics: BarChart3,

  // Invites
  createInvite: UserPlus2,
  copyInviteLink: ClipboardCopy,
  deleteInvite: Trash2,
  createUserInvitationPlus: UserPlus2,
  linkCopy: ClipboardCopy,
  invitationInbox: MailOpen,
  deleteInvitation: Trash2,

  // New feature icons
  view: Eye,
  date: CalendarIcon,
  caseNumber: ScaleIcon,
  user: UserIcon,
  parties: UserIcon,
  advocates: UsersIcon,
  advocate: UserIcon,
  court: LibraryIcon,
  caseFile: FileTextIcon,
  caseImportPending: Clock,
  caseImportInProgress: Loader2,
  caseImportCompleted: CheckCircle,
  caseImportFailed: XCircle,
  caseImportRefresh: RefreshCw,
  caseImportRefreshLoading: Loader2,
  caseImportRetry: RotateCw,
  caseImportCancel: X,
  print: Printer,

  // Feature icons
  featureCaseManagement: FileText,
  featureCalendar: Calendar,
  featureTeam: Users,
  featureAnalytics: BarChart3,
};
