import {
  ArrowRight,
  CalendarIcon,
  Eye,
  Files,
  FileTextIcon,
  LibraryIcon,
  LoaderCircle,
  PanelsTopLeft,
  Pencil,
  ScaleIcon,
  UserIcon,
  UsersIcon,
} from "lucide-react";

export const Icons = {
  cases: Files,
  rightArrow: ArrowRight,
  loading: LoaderCircle,
  sidebar: PanelsTopLeft,
  edit: Pencil,
  view: Eye,
  date: CalendarIcon,
  caseNumber: ScaleIcon,
  user: UserIcon,
  parties: UserIcon,
  advocates: UsersIcon,
  advocate: UserIcon,
  court: LibraryIcon,
  caseFile: FileTextIcon,
};
