import {
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Building2,
  Calendar,
  CalendarIcon,
  CheckCircle,
  Clock,
  Eye,
  Files,
  FileText,
  FileTextIcon,
  LibraryIcon,
  Loader2,
  LoaderCircle,
  PanelsTopLeft,
  Pencil,
  Printer,
  RefreshCw,
  RotateCw,
  ScaleIcon,
  UserIcon,
  Users,
  UsersIcon,
  X,
  XCircle,
} from "lucide-react";

export const Icons = {
  cases: Files,
  rightArrow: ArrowRight,
  externalLink: ArrowUpRight,
  organization: Building2,
  loading: LoaderCircle,
  sidebar: PanelsTopLeft,
  edit: Pencil,
  view: Eye,
  date: CalendarIcon,
  caseNumber: ScaleIcon,
  user: UserIcon,
  parties: UserIcon,
  advocates: UsersIcon,
  advocate: UserIcon,
  court: LibraryIcon,
  caseFile: FileTextIcon,
  caseImportPending: Clock,
  caseImportInProgress: Loader2,
  caseImportCompleted: CheckCircle,
  caseImportFailed: XCircle,
  caseImportRefresh: RefreshCw,
  caseImportRefreshLoading: Loader2,
  caseImportRetry: RotateCw,
  caseImportCancel: X,
  print: Printer,
  // Feature icons
  featureCaseManagement: FileText,
  featureCalendar: Calendar,
  featureTeam: Users,
  featureAnalytics: BarChart3,
};
